openapi: "3.0.0"
info:
  title: "pms API"
  description: "pms API"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000/api/v1"
paths:
  /api/v1/auth/login:
    post:
      summary: "POST api/v1/auth/login"
      operationId: "login"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
  /api/v1/auth/signup:
    post:
      summary: "POST api/v1/auth/signup"
      operationId: "signUp"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertUserDTO"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
  /api/v1/users:
    get:
      summary: "GET api/v1/users"
      operationId: "findAllUsers"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /api/v1/projects/{projectId}:
    put:
      summary: "PUT api/v1/projects/{projectId}"
      operationId: "updateProject"
      parameters:
        - name: "projectId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertProjectDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Project"
    delete:
      summary: "DELETE api/v1/projects/{projectId}"
      operationId: "deleteProject"
      parameters:
        - name: "projectId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "204":
          description: "No Content"
    get:
      summary: "GET api/v1/projects/{projectId}"
      operationId: "getProjectById"
      parameters:
        - name: "projectId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Project"
  /api/v1/projects:
    post:
      summary: "POST api/v1/projects"
      operationId: "createProject"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertProjectDTO"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Project"
    get:
      summary: "GET api/v1/projects"
      operationId: "getAllProjects"
      parameters:
        - name: "pageNo"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "0"
        - name: "pageSize"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "10"
        - name: "sortBy"
          in: "query"
          required: false
          schema:
            type: "string"
            default: "id"
        - name: "sortDirection"
          in: "query"
          required: false
          schema:
            type: "string"
            default: "ASC"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ProjectDTO"
  /api/v1/projects/{projectId}/expenses/{expenseId}:
    put:
      summary: "PUT api/v1/projects/{projectId}/expenses/{expenseId}"
      operationId: "updateProjectExpense"
      parameters:
        - name: "projectId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
        - name: "expenseId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectExpenseDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProjectExpense"
    delete:
      summary: "DELETE api/v1/projects/{projectId}/expenses/{expenseId}"
      operationId: "deleteProjectExpense"
      parameters:
        - name: "projectId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
        - name: "expenseId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "204":
          description: "No Content"
  /api/v1/projects/{projectId}/expenses:
    post:
      summary: "POST api/v1/projects/{projectId}/expenses"
      operationId: "createProjectExpense"
      parameters:
        - name: "projectId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectExpenseDTO"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProjectExpense"
components:
  schemas:
    UserLoginDTO:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
    AuthenticationResponse:
      type: "object"
      properties:
        access_token:
          type: "string"
        refresh_token:
          type: "string"
    UpsertUserDTO:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
    ProjectDetailsDTO:
      type: "object"
      properties:
        description:
          type: "string"
        imagesFolderURL:
          type: "string"
    UpsertProjectDTO:
      type: "object"
      properties:
        title:
          type: "string"
        minAge:
          type: "integer"
          format: "int32"
        maxAge:
          type: "integer"
          format: "int32"
        price:
          type: "number"
          format: "double"
        location:
          type: "string"
        projectDetails:
          $ref: "#/components/schemas/ProjectDetailsDTO"
    ProjectDetails:
      type: "object"
      properties:
        description:
          type: "string"
        imagesFolderURL:
          type: "string"
        id:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
    ProjectExpense:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        price:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
    Project:
      type: "object"
      properties:
        title:
          type: "string"
        minAge:
          type: "integer"
          format: "int32"
        maxAge:
          type: "integer"
          format: "int32"
        price:
          type: "number"
          format: "double"
        location:
          type: "string"
        projectDetails:
          $ref: "#/components/schemas/ProjectDetails"
        projectExpenses:
          type: "array"
          items:
            $ref: "#/components/schemas/ProjectExpense"
        id:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
    ProjectDTO:
      type: "object"
      properties:
        title:
          type: "string"
        minAge:
          type: "integer"
          format: "int32"
        maxAge:
          type: "integer"
          format: "int32"
        price:
          type: "number"
          format: "double"
        location:
          type: "string"
        projectDetails:
          $ref: "#/components/schemas/ProjectDetails"
        id:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
    ProjectExpenseDTO:
      type: "object"
      properties:
        name:
          type: "string"
        price:
          type: "integer"
          format: "int32"