services:
  postgres:
    container_name: postgres
    image: postgres:15.6
    environment:
      POSTGRES_USER: trainopia
      POSTGRES_PASSWORD: trainopia
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: trainopia@gmail.com
      PGADMIN_DEFAULT_PASSWORD: trainopia
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
volumes:
  pgdata:
  pgadmin-data: